main1:main1.c process1.c
	@# @gcc -o $@ $^
	@gcc main1.c process1.c -o main1
clean1:
	@rm -rf main1 

main2:main2.c process2.c
	@# @gcc -o $@ $^
	@gcc main2.c process2.c -o main2
clean2:
	@rm -rf main2
